name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: project/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: project
      - name: Lint
        run: npm run lint
        working-directory: project
      - name: Build
        run: npm run build
        working-directory: project
        continue-on-error: true
